version: '3.1'
services: 
    homeassistant:
        image: homeassistant/home-assistant:latest
        container_name: homeassistant
        ports:  
            - 8123:8123
        volumes:
            - ${PWD}/custom_components:/config/custom_components
            - ${PWD}/configuration.yaml:/config/configuration.yaml